Repository Stark1392/C-Programmes, pull requests merged in 2022-10, with the labels that each got.

#7 Update printf.c
  printf.c
Labels: hacktoberfest-accepted

#12 added table of 1-10
  sum.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#11 Create simple calculator
  simple calculator
Labels: hactoberfest-accepted, hacktoberfest-accepted

#10 Create C break and continue
  C break and continue
Labels: hactoberfest-accepted, hacktoberfest-accepted

#9 Create For Loop
  For Loop
Labels: hactoberfest-accepted, hacktoberfest-accepted

#8 Create fibonaccci
  fibonaccci
Labels: hactoberfest-accepted, hacktoberfest-accepted

#24 Update tax.c
  tax.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#27 Update TCP Socket server
  TCP Socket server
Labels: hactoberfest-accepted, hacktoberfest-accepted

#28 Create TCP Client Socket
  TCP Client Socket
Labels: hactoberfest-accepted, hacktoberfest-accepted

#23 Create Reverse an Integer
  Reverse an Integer
Labels: hactoberfest-accepted, hacktoberfest-accepted

#22 Create LCM Calculation Using GCD
  LCM Calculation Using GCD
Labels: hactoberfest-accepted, hacktoberfest-accepted

#21 Create LCM using while and if
  LCM using while and if
Labels: hactoberfest-accepted, hacktoberfest-accepted

#20 Create Read Input Until a Positive Integer is Entered
  Read Input Until a Positive Integer is Entered
Labels: hactoberfest-accepted, hacktoberfest-accepted

#19 Create Sum of Natural Numbers Using while Loop
  Sum of Natural Numbers Using while Loop
Labels: hactoberfest-accepted, hacktoberfest-accepted

#18 Create Sum of Natural Numbers Using for Loop
  Sum of Natural Numbers Using for Loop
Labels: hactoberfest-accepted, hacktoberfest-accepted

#17 Create Swap Numbers Using Temporary Variable
  Swap Numbers Using Temporary Variable
Labels: hactoberfest-accepted, hacktoberfest-accepted

#15 Create Program to Print ASCII Value
  Program to Print ASCII Value
Labels: hactoberfest-accepted, hacktoberfest-accepted

#14 Create Program to Add Two Integers
  Program to Add Two Integers
Labels: hactoberfest-accepted, hacktoberfest-accepted

#13 Create Program to Add Two Matrices
  Program to Add Two Matrices
Labels: hactoberfest-accepted, hacktoberfest-accepted

#39 Create ifelse.c
  ifelse.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#42 Create poll_server.c
  poll_server.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#41 Create fork_server.c
  fork_server.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#40 Create select_server.c
  select_server.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#45 Create concurrentServer
  concurrentServer
Labels: hactoberfest-accepted, hacktoberfest-accepted

#44 Create sequentialClient.c
  sequentialClient.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#43 Create sequentialServer.c
  sequentialServer.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#48 merging2sortedarrays.c
  merging2sortedarrays.c
Labels: good first issue, hacktoberfest-accepted

#46 Palindrome.c
  Palindrome.c
Labels: good first issue, hacktoberfest-accepted

#38 Create C Program to Store Data in Structures Dynamically
  C Program to Store Data in Structures Dynamically
Labels: hactoberfest-accepted, hacktoberfest-accepted

#37 Create C Program to Add Two Distances (in inch-feet system) using Str…
  C Program to Add Two Distances (in inch-feet system) using Structures
Labels: good first issue, hacktoberfest-accepted

#35 Create C Program to Concatenate Two Strings
  C Program to Concatenate Two Strings
Labels: hactoberfest-accepted, hacktoberfest-accepted

#34 Create C Program to Find the Length of a String
  C Program to Find the Length of a String
Labels: hactoberfest-accepted, hacktoberfest-accepted

#33 Create GCD of Two Numbers using Recursion
  GCD of Two Numbers using Recursion
Labels: hactoberfest-accepted, hacktoberfest-accepted

#32 Create C program to calculate the power using recursion
  C program to calculate the power using recursion
Labels: hactoberfest-accepted, hacktoberfest-accepted

#31 Create C Program to Calculate Average Using Arrays
  C Program to Calculate Average Using Arrays
Labels: hactoberfest-accepted, hacktoberfest-accepted

#30 Create Program to Find the Transpose of a Matrix
  Program to Find the Transpose of a Matrix
Labels: hactoberfest-accepted, hacktoberfest-accepted

#50 Program to Print an Integer
  C Program to Print an Integer
  Find length of loop/cycle in given Linked List
Labels: hactoberfest-accepted, hacktoberfest-accepted

#51 Create C Program to Multiply Two Floating-Point Numbers
  C Program to Multiply Two Floating-Point Numbers
Labels: hactoberfest-accepted, hacktoberfest-accepted

#52 Create C Program to Swap Two Numbers
  C Program to Swap Two Numbers
Labels: hactoberfest-accepted, hacktoberfest-accepted

#55 Create C Program to Check Whether a Number is Positive or Negative
  C Program to Check Whether a Number is Positive or Negative
Labels: hactoberfest-accepted, hacktoberfest-accepted

#54 Create C Program to Check Leap Year
  C Program to Check Leap Year
Labels: hactoberfest-accepted, hacktoberfest-accepted

#57 Some Java codes
  best time to buy and sell stocks
  flatten binary tree to linked list
  longest consecutive sequence
Labels: hactoberfest-accepted, hacktoberfest-accepted

#59 mark 42
  Shortest Uncommon Subsequence
  jump game 3
  rotate array
  wiggle subsequence
Labels: hactoberfest-accepted, hacktoberfest-accepted

#60 Create implement strstr
  implement strstr
Labels: hactoberfest-accepted, hacktoberfest-accepted

#61 Add files via upload
  Add_256bit_int.c
  Copy_src_to_dest_file.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#63 Add files via upload
  swap_two_arrays.c
Labels: good first issue, hacktoberfest-accepted

#62 Prime Number
  Prime Number
Labels: hactoberfest-accepted, hacktoberfest-accepted

#64 C program to reverse a string and then print it
  reverse_ a_string.c
Labels: good first issue, hacktoberfest-accepted

#65 Add files via upload
  sort_array_find_element.c
Labels: good first issue, hacktoberfest-accepted

#68 Create play with colors
  play with colors
Labels: hactoberfest-accepted, hacktoberfest-accepted

#66 Create Program to find Sparse Matrix
  Program to find Sparse Matrix
Labels: hactoberfest-accepted, hacktoberfest-accepted

#70 Create infixtopostfix.c
  infixtopostfix.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#69 Create PolynomialEvaluation.c
  PolynomialEvaluation.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#71 3D-Array with C
  3DArray.c
Labels: hactoberfest-accepted, hacktoberfest-accepted
